services:
  nest-clean-architecture-db:
    image: pgvector/pgvector:pg17
    container_name: nest-clean-architecture-db
    environment:
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - nest-clean-architecture-db:/data/postgres
    ports:
      - 5432:5432
    networks:
      - network
    restart: always
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  nest-clean-architecture-db:
  ollama-data:
networks:
  network:
    driver: bridge
