export const USER_SERVICE = 'USER_SERVICE';
export const GEOCODING_SERVICE = 'GEOCODING_SERVICE';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
export const CHATBOT_SERVICE = 'CHATBOT_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const NOTIFICATION_BROADCAST_SERVICE = 'NOTIFICATION_BROADCAST_SERVICE';
export const EMAIL_SERVICE = 'EMAIL_SERVICE';
